services:

  backend:

    build:
      context: ./backend  # Diretório onde está o código do Laravel
      dockerfile: Dockerfile  # Arquivo Dockerfile para o backend
    container_name: laravel_backend
    ports:
      - "8000:8000"  # Mapeia a porta 8000 do host para o container
    volumes:
      - ./backend:/var/www/html  # Monta o código local no container
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    networks:
      - app-network 

  frontend:
     build:
       context: ./frontend  # Diretório onde está o código do Nuxt.js
       dockerfile: Dockerfile  # Arquivo Dockerfile para o frontend
     container_name: nuxt_frontend
     ports:
       - "3000:3000"  # Porta padrão do Nuxt.js
     volumes:
       - ./frontend:/app  # Monta o código local no container
     environment:
       NODE_ENV: development
       NUXT_HOST: 0.0.0.0
       NUXT_PORT: 3000
       API_URL: http://backend:8000  # URL do backend interno
     networks:
       - app-network

# Rede para comunicação entre os serviços
networks:
  app-network:
    driver: bridge